### ISSUE TITLE
@nteract/jupyter-widgets doesn't work on non-redux projects

### ISSUE THREAD

**Issue by jcleyba** [nteract/outputs#23]
Looks like the Manager component in the jupyter-widgets package only exports a connected component causing it to fail when it's required outside of a redux store context.

The error reads: `Could not finde "store" in the context of "Connect(Manager)"` 

![image](https://user-images.githubusercontent.com/9270758/94735314-f188d980-0340-11eb-99d0-dfe69c36fa2f.png)

The main component that the library exports (`WidgetDisplay`) can be imported anyway because the class is also exported.

Can this Manager be decoupled from redux?

Thanks!!

@captainsafia

**Comment by captainsafia** [comment]
Thanks for opening this issue, @jcleyba!

Took a look into it and you're correct. There's two things going on here:

- We don't export the unconnected Manager from `jupyter-widgets/manager/index.tsx` for use.
- The `WidgetDisplay` implementation uses the connected manager.

I'm working on a fix for the first issue which should enable you to do the following to resolve your problem.

```js
import { UnconnectedManager } from "@nteract/jupyter-widgets/lib/manager";

class MyWidget extends React.Component {
    render() {
       <UnconnectedManager props={...} />
    }
}
```

The `BackboneWrapper`, `WidgetManager`, and `WidgetComm` elements don't need access to the Redux store. You'll have to provide a `kernel` to the `UnconnectedManager` that is a `RemoteKernel` type supported by nteract though.

Let me know if this is helpful!

**Comment by jcleyba** [comment]
Hi @captainsafia, thanks for your answer. This is very helpful. an unconnected manager would solve the issue and prevent apps crashing when using this component. Would `WidgetDisplay` need to receive the new manager as prop? or maybe some other way?

Thanks again!

**Comment by captainsafia** [comment]
> Would WidgetDisplay need to receive the new manager as prop? or maybe some other way?

`WidgetDisplay` won't come into play here. My example above is incomplete. The `MyWidget` component above is an unconnected re-implementation of the WidgetDisplay.

https://github.com/nteract/outputs/blob/d2be0c41c7c316055470eddf3a40c848ca4f5704/packages/jupyter-widgets/src/index.tsx#L46-L80

A more accurate name for the component above would've been `MyWidgetDisplay`.

**Comment by jcleyba** [comment]
@captainsafia Gotcha. Sounds awesome! Let me know if I can be of any help.

**Comment by captainsafia** [comment]
OK, @jcleyba! @nteract/jupyter-widgets@4.4.13 is released now which exports the unconnected Manager component. I'm going to close this issue now. If you run into issues with the integration, can you open a question at https://github.com/nteract/nteract/discussions. Thanks!
